ETF-TAK/BE

- build.gradle
- src/main/java/com/example/tak/config/SwaggerConfig.java
> pr settings/#2-settings-swagger

- build.gradle
- src/main/java/com/example/tak/domain/Distribution.java
- src/main/java/com/example/tak/domain/ETF.java
- src/main/java/com/example/tak/domain/Stock.java
> pr feat/#7-add-entity

- src/main/java/com/example/tak/common/Category.java
- src/main/java/com/example/tak/domain/ETF.java
> pr feat/#9-etf-category-enum-type

- src/main/java/com/example/tak/common/Category.java
- src/main/java/com/example/tak/common/Nation.java
- src/main/java/com/example/tak/domain/ETF.java
- src/main/resources/application.yml
> pr feat/#11-enum-nation

- src/main/java/com/example/tak/common/Category.java
- src/main/java/com/example/tak/common/Nation.java
- src/main/java/com/example/tak/converter/CategoryConverter.java
- src/main/java/com/example/tak/converter/NationConverter.java
- src/main/java/com/example/tak/domain/ETF.java
> pr feat/#17-add-converter

- src/main/java/com/example/tak/domain/ETF.java
> pr feat/#20-etf-unused-field-remove

- src/main/resources/application.yml
- rds 엔드포인트와 계정, 비밀번호 정보를 추가했습니다.
> pr settings/#19-make-dockerfile

- .gitignore
> pr settings/#24-env-file-gitignore-addition

- deploy.sh
> pr feat/#25-feature-deploy-script

- src/main/java/com/example/tak/controller/EtfCompareController.java
- src/main/java/com/example/tak/dto/response/ComponentStockInfo.java
- src/main/java/com/example/tak/dto/response/CurrentPriceData.java
- src/main/java/com/example/tak/dto/response/DistributionInfo.java
- src/main/java/com/example/tak/dto/response/EtfDetailResponse.java
- src/main/java/com/example/tak/dto/response/EtfDetailResult.java
- src/main/java/com/example/tak/dto/response/HistoricalPriceResponse.java
- src/main/java/com/example/tak/dto/response/MarketPriceResponse.java
- src/main/java/com/example/tak/repository/EtfRepository.java
- src/main/java/com/example/tak/service/ComponentStockService.java
- src/main/java/com/example/tak/service/DistributionService.java
- src/main/java/com/example/tak/service/DividendService.java
- src/main/java/com/example/tak/service/EtfComparisonService.java
- src/main/java/com/example/tak/service/EtfDetailService.java
- src/main/java/com/example/tak/service/EtfInfoService.java
- src/main/java/com/example/tak/service/PriceService.java
- src/main/java/com/example/tak/service/StockInfoService.java
- src/main/java/com/example/tak/service/UsDistributionService.java
- src/main/java/com/example/tak/service/UsPriceService.java
> pr feat/#32-etf-detail-page

- src/main/java/com/example/tak/controller/ETFInvestListController.java
- src/main/java/com/example/tak/dto/response/ETFInvestListResponseDTO.java
- src/main/java/com/example/tak/repository/EtfDataRepository.java
- src/main/java/com/example/tak/service/ETFInvestListService.java
> pr feat/#38-get-etf-invest-list

- src/main/java/com/example/tak/controller/EtfCompareController.java
- src/main/java/com/example/tak/dto/response/EtfResponseDto.java
- src/main/java/com/example/tak/repository/EtfRepository.java
- src/main/java/com/example/tak/service/EtfCompareListService.java
#29 
- ETF 비교화면 카테고리별 검색 API를 구현합니다.
> feat: ETF 비교화면 카테고리별 검색 API 구현

- src/main/java/com/example/tak/controller/ETFInvestController.java
- src/main/java/com/example/tak/dto/request/ETFInvestRequestDto.java
- src/main/java/com/example/tak/dto/response/ETFInvestResponseDto.java
- src/main/java/com/example/tak/repository/EtfDataRepository.java
- src/main/java/com/example/tak/service/ETFInvestService.java
- src/main/java/com/example/tak/service/InvestPriceService.java
- src/main/java/com/example/tak/service/UsInvestService.java
#44 
- ETF 투자하기 기능 (POST)을 구현합니다.
- 한국과 미국 ETF의 1년 전 대비 수익과 수익률을 구하는 서비스 코드를 구현했습니다.
> pr Feat/#29 etf search

- src/main/java/com/example/tak/controller/ETFInvestListController.java
- src/main/java/com/example/tak/repository/EtfDataRepository.java
- src/main/java/com/example/tak/service/ETFInvestListService.java
ETF 투자하기 목록 조회 API에 한국과 미국 조회를 추가하였습니다.
> pr feat/#43-get-etf-invest-list-ko-en

- src/main/java/com/example/tak/controller/ETFInvestListController.java
- src/main/java/com/example/tak/controller/EtfCompareController.java
- src/main/java/com/example/tak/dto/response/EtfResponseDto.java
- src/main/java/com/example/tak/service/EtfGetListService.java
> pr feat: ETF 리스트 둘러보기 기능 구현

- src/main/java/com/example/tak/service/InvestPriceService.java
- src/main/java/com/example/tak/service/UsInvestService.java
> feat: 미국 ETF 환율 적용

- src/main/java/com/example/tak/service/EtfGetListService.java
> pr fix: 현재가 구하는 메서드 수정

- src/main/java/com/example/tak/service/EtfGetListService.java
> pr feat(#46): ETF 둘러보기 현재가에 환율 적용

- src/main/java/com/example/tak/service/EtfGetListService.java
- src/main/java/com/example/tak/service/UsPriceService.java
> fix(#46): 미국 ETF 환율 재적용

- src/main/java/com/example/tak/dto/response/EtfInfoResponse.java
- src/main/java/com/example/tak/dto/response/EtfResponseDto.java
- src/main/java/com/example/tak/service/EtfGetListService.java
- src/main/java/com/example/tak/service/EtfInfoService.java
- 구현 내용
- ETF 비교 화면 응답 바디 (ticker, etfNum, secotr) 에 데이터를 추가했습니다.
> fix(#46): ETF 비교 화면 응답값 추가 (ticker, etfNum, secotr)

- src/main/java/com/example/tak/service/UsPriceService.java
- 현재가에 대해서 환율 적용하는 부분을 수정했습니다.
> pr fix(#46): 환율 적용 수정

- src/main/java/com/example/tak/service/ComponentStockService.java
- src/main/java/com/example/tak/service/EtfDetailService.java
- src/main/java/com/example/tak/service/UsPriceService.java
> pr fix/#66-edit-decimal-point-to-one-digit

- src/main/java/com/example/tak/service/EtfInfoService.java
- 미국 ETF 상세정보를 불러오는 코드에 섹터 부분을 추가했습니다.
> pr fix(#46): 미국 ETF 상세 정보 sector 추가

- src/main/java/com/example/tak/domain/ETF.java
- src/main/java/com/example/tak/dto/response/EtfResponseDto.java
> pr fix/#72-fee-type

- src/main/java/com/example/tak/dto/response/EtfResponseDto.java
- src/main/java/com/example/tak/service/ETFInvestService.java
> pr Feat/#70 add null value 
